### ISSUE TITLE
Installer prefers python36-robotpy-cscore 2017.0.0rc3 over 2017.0.0

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-installer#12]
From a quick glance at the installer source, it looks like the installer will just look at the last instance of the package declared in the Packages file?

**Comment by virtuald** [comment]
No, it uses `LooseVersion` to order the packages ([see line 127](https://github.com/robotpy/robotpy-installer/blob/master/robotpy_installer/installer.py#L127)). I did an installation with opkg, and it prefers 2017.0.0rc3 over 2017.0.0 as well, so the problem is with the version scheme I'm using, not the installer. I'm planning to push a new cscore release tonight anyways, so this should hopefully be moot.
